### ISSUE TITLE
How does this differ from the original freeshop?

### ISSUE THREAD

**Issue by danimesq** [Ghost0159/freeshop#1]

**Comment by Ghost0159** [comment]
There is nothing different, this is the source code of the freeshop when it worked

**Comment by danimesq** [comment]
I've made a private archived repo with all of the commits including those from forks: https://github.com/danimesq/freeShop

Its private bc I fear a DMCA as it happened to the original one

**Comment by Ghost0159** [comment]
Ok, nice

**Comment by danimesq** [comment]
BTW, what is your current project? Beeshop or GhostShop? And what about hshop?

**Comment by Ghost0159** [comment]
Sorry for my delay in answering, beeshop is abandoned, Ghost eShop is my current project on which I work with different people, even if for personal reasons I can't work on it for a while.
And for hshop, it's a good project, but it's not mine nor Ghost eShop's.
